version: "3.8"
services:
  frontend:
    build: ./frontend/vite-project
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - default

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - default

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db-data:

networks:
  default:
    driver: bridge
